"""Remove service_id from BlogPost

Revision ID: f7c3b685b8a2
Revises: 80f39a418cb1
Create Date: 2025-02-03 16:32:26.581438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7c3b685b8a2'
down_revision = '80f39a418cb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_constraint('blogs_service_id_fkey', type_='foreignkey')
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('blogs_service_id_fkey', 'services', ['service_id'], ['id'])

    # ### end Alembic commands ###
